# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cris/CLionProjects/hydrogen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cris/CLionProjects/hydrogen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/cris/CLionProjects/hydrogen && $(CMAKE_COMMAND) -E cmake_progress_start /home/cris/CLionProjects/hydrogen/CMakeFiles /home/cris/CLionProjects/hydrogen/libs/stb//CMakeFiles/progress.marks
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs/stb/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cris/CLionProjects/hydrogen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs/stb/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs/stb/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs/stb/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/cris/CLionProjects/hydrogen && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
libs/stb/CMakeFiles/stb.dir/rule:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs/stb/CMakeFiles/stb.dir/rule
.PHONY : libs/stb/CMakeFiles/stb.dir/rule

# Convenience name for target.
stb: libs/stb/CMakeFiles/stb.dir/rule
.PHONY : stb

# fast build rule for target.
stb/fast:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f libs/stb/CMakeFiles/stb.dir/build.make libs/stb/CMakeFiles/stb.dir/build
.PHONY : stb/fast

stb_vorbis.o: stb_vorbis.c.o
.PHONY : stb_vorbis.o

# target to build an object file
stb_vorbis.c.o:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f libs/stb/CMakeFiles/stb.dir/build.make libs/stb/CMakeFiles/stb.dir/stb_vorbis.c.o
.PHONY : stb_vorbis.c.o

stb_vorbis.i: stb_vorbis.c.i
.PHONY : stb_vorbis.i

# target to preprocess a source file
stb_vorbis.c.i:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f libs/stb/CMakeFiles/stb.dir/build.make libs/stb/CMakeFiles/stb.dir/stb_vorbis.c.i
.PHONY : stb_vorbis.c.i

stb_vorbis.s: stb_vorbis.c.s
.PHONY : stb_vorbis.s

# target to generate assembly for a file
stb_vorbis.c.s:
	cd /home/cris/CLionProjects/hydrogen && $(MAKE) $(MAKESILENT) -f libs/stb/CMakeFiles/stb.dir/build.make libs/stb/CMakeFiles/stb.dir/stb_vorbis.c.s
.PHONY : stb_vorbis.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stb"
	@echo "... stb_vorbis.o"
	@echo "... stb_vorbis.i"
	@echo "... stb_vorbis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/cris/CLionProjects/hydrogen && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

